POST http://localhost:3003/user/recover
 Content-Type: application/json

{
    "email":"tesfdsgfffkdfde@ftste.com"
}

###

POST http://localhost:3003/user/change?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjE5MDZiYzk5LTNjM2UtNGUwNy1iYWY3LTgwODNmNzAxMmIyNiJ9LCJpYXQiOjE2MzAzNDg0MzksImV4cCI6MTYzMDQzNDgzOX0.-7xuNiclLRw3GIWaHInwUg-vV2tq8Pp6Aq_Qr5NNqfk
 Content-Type: application/json

{
    "password":"tesfdsgfffkdfde@ftste.com"   
}

